before_script:
    - php -v
    - pwd

cache:
  paths:
    - vendor/
  untracked: true

stages:
  - test
  - deploy

test:
    stage: test
    script:
        - sudo /usr/local/bin/composer self-update
        - /usr/local/bin/composer install --no-interaction -q
        - vendor/bin/phpunit
    #except:
        #- master

deploy:
    type: deploy
    script:
        - eb --version
        - eb use tootlog-dev
        - eb deploy
    only:
        - master
