sudo: false
language: php

php:
- '7.1'

before_script:
  - phpenv config-rm xdebug.ini
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --no-progress --no-suggest

branches:
  only:
    - master

cache:
  directories: vendor

script:
- vendor/bin/phpunit

after_success:
   - curl -s "$FORGE";
