branch-defaults:
  master:
    environment: tootlog-dev
global:
  application_name: tootlog
  branch: null
  default_ec2_keyname: backend
  default_platform: PHP 7.0
  default_region: ap-northeast-1
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
